---
services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=Etc/UTC
    volumes:
      - ./config:/config
    # ports:
      # - 3023:3000 # commented out because of network mode host
      # - 4023:3001 #commented out because of network mode host
