---
# Netpi Config File #

## ZSH Shell
#
# Install the ZSH shell with oh-my-zsh plugin and theming framework
install_ohmyzsh: false
ohmyzsh_theme:                       # Themes can be found here: https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ohmyzsh_plugins:                     # List plugins one by one separated with space. Plugins can be found here: https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins

## Automatic upgrades
#
# Define if you want to enable automatic upgrades and if so only security or also all other updates
automatic_updates: false
security_updates_only: true
automatic_reboot: false     # Should the system automaticaly be rebootet if it is necessary after an update

## IP for dashboard
#
# Define if the ip for the dashboard tools should be automaticaly fetched from the system after every reboot
# or staticly configured
dash_auto_ip: true
dash_static_ip:        # only set this if dash_auto_ip is equal to false. write ip address for example "192.168.1.5"

