---
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    # - TZ=Etc/UTC
      - PASSWORD=password
    volumes:
      - ./config:/config
    ports:
      - 3013:80