---
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{ timezone }}
      - PASSWORD=PASSWORD
    volumes:
      - /opt/docker/librespeed/config:/config
    ports:
      - 3002:80
    restart: unless-stopped