---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    hostname: syncthing-netpi #optional
    environment:
      - PUID=1000
      - PGID=1000
     # - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 4020:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp