---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Netpi"
subtitle: "Dashboard"
logo: assets/logos/netpi.png
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Powered by Homer. Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

connectivityCheck: true

# Set the default layout and color scheme
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#363636"
    highlight-secondary: "#424242"
    highlight-hover: "#5a95f5"
      # background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "../assets/bg/fiber3.jpg"
  dark:
    highlight-primary: "#363636"
    highlight-secondary: "#424242"
    highlight-hover: "#5a95f5"
    #    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "../assets/bg/fiber3.jpg"

# Optional message
# message:
  #url: https://b4bz.io
  # style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  # title: "Demo !"
  # icon: "fa fa-grin"
  # content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []
  # - name: "Contribute"
    # icon: "fab fa-github"
    # url: "https://github.com/bastienwirtz/homer"
    # target: "_blank" # optional html a tag target attribute
  # - name: "Wiki"
    # icon: "fas fa-book"
    # url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Management"
    icon: "fas fa-cubes"
    items:
      - name: "Dockge"
        logo: "assets/logos/dockge.png"
        type: Ping
        subtitle: "Docker container management"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:5001"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:5001"
        target: '_blank'

      - name: "Cockpit"
        logo: "assets/logos/cockpit.png"
        type: Ping
        subtitle: "Web-based graphical interface for servers"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:9090"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:9090"
        target: '_blank'

      - name: "Wetty"
        logo: "assets/logos/wetty.png"
        type: Ping
        subtitle: "SSH Web-Terminal for Netpi"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:3033"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3033/wetty"
        target: '_blank'

  - name: "Monitoring and performance testing"
    icon: "fas fa-eye"
    items:
      - name: "Uptime Kuma"
        logo: "assets/logos/uptimekuma.png"
        type: Ping
        subtitle: "Monitoring tool"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:3006"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3006"
        target: '_blank'

      - name: "SmokePing"
        logo: "assets/logos/smokeping.png"
        type: Ping
        subtitle: "Network latency monitoring"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:81"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:81"
        target: '_blank'

      - name: "Statping"
        logo: "assets/logos/statping.png"
        type: Ping
        subtitle: "Status page for monitoring websites and applications"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:8080"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:8080"
        target: '_blank'

      - name: "Open SpeedTest"
        logo: "assets/logos/openspeedtest.png"
        type: Ping
        subtitle: "Local Network Speed Test"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:3008"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:3008"
        target: '_blank'

      - name: "LibreSpeed Test"
        logo: "assets/logos/librespeedtest.svg"
        type: Ping
        subtitle: "Local Network Speed Test"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:3080"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3080"
        target: '_blank'

      - name: "Speedtest Tracker"
        logo: "assets/logos/speedtest-tracker.png"
        type: Ping
        subtitle: "Internet speedtest perfomance tracker"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:4080"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:4080"
        target: '_blank'

  - name: "Other Applications"
    icon: "fas fa-database"
    items:
      - name: "Wireshark"
        logo: "assets/logos/wireshark.png"
        type: Ping
        subtitle: "Network protocol analyzer"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:3001"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:3001"
        target: '_blank'

      - name: "SFTPGo"
        logo: "assets/logos/sftpgo.png"
        type: Ping
        subtitle: "SFTP server"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:8088"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:8088"
        target: '_blank'

      - name: "Chromium"
        logo: "assets/logos/chromium.svg"
        type: Ping
        subtitle: "Web browser"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:3005"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:3005"
        target: '_blank'

      - name: "Syncthing"
        logo: "assets/logos/syncthing.png"
        type: Ping
        subtitle: "File synchronization"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:8384"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:8384"
        target: '_blank'