---
services:
  statping:
    container_name: statping
    image: statping/statping:latest
    restart: always
    volumes:
      - statping_data:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 3019:8080

volumes:
  statping_data: