---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Netpi"
subtitle: "Dashboard"
logo: assets/logos/netpi_logo_black.svg
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Powered by Homer. Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

connectivityCheck: true

# Set the default layout and color scheme
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: dark # One of 'auto', 'light', or 'dark'

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#ffffff"
    highlight-secondary: "#f5f5f5"
    highlight-hover: "#5a95f5"
      # background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#000000"
    text-header: "#000000"
    text-title: "#000000"
    text-subtitle: "#000000"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "../assets/bg_white.jpg"
  dark:
    highlight-primary: "#363636"
    highlight-secondary: "#424242"
    highlight-hover: "#5a95f5"
    #    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "../assets/bg_dark.jpg"

# Optional message
# message:
  #url: https://b4bz.io
  # style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  # title: "Demo !"
  # icon: "fa fa-grin"
  # content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/SG303/netpi"
    target: "_blank" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Management"
    icon: "fas fa-cubes"
    items:
      - name: "Dockge"
        logo: "assets/logos/dockge.png"
        type: Ping
        subtitle: "Docker container management"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:3012"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3012"
        target: '_blank'

      - name: "Cockpit"
        logo: "assets/logos/cockpit.png"
        type: Ping
        subtitle: "Web-based server management"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:9090"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:9090"
        target: '_blank'

      - name: "Wetty"
        logo: "assets/logos/wetty.png"
        type: Ping
        subtitle: "SSH web-terminal"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:4022/wetty"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:4022/wetty"
        target: '_blank'

  - name: "Monitoring and performance testing"
    icon: "fas fa-eye"
    items:
      - name: "Uptime Kuma"
        logo: "assets/logos/uptimekuma.png"
        type: Ping
        subtitle: "Monitoring tool"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:3021"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3021"
        target: '_blank'

      - name: "SmokePing"
        logo: "assets/logos/smokeping.png"
        type: Ping
        subtitle: "Network latency monitoring"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:3017"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3017"
        target: '_blank'

      - name: "Statping"
        logo: "assets/logos/statping.png"
        type: Ping
        subtitle: "Service health monitor"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:3019"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3019"
        target: '_blank'

      - name: "Open SpeedTest"
        logo: "assets/logos/openspeedtest.png"
        type: Ping
        subtitle: "Local network speed test"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:4014"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:3014"
        target: '_blank'

      - name: "LibreSpeed Test"
        logo: "assets/logos/librespeedtest.svg"
        type: Ping
        subtitle: "Local network speed test"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:3013"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3013"
        target: '_blank'

      - name: "Speedtest Tracker"
        logo: "assets/logos/speedtest-tracker.png"
        type: Ping
        subtitle: "Internet speedtest perfomance tracker"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:3018"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3018"
        target: '_blank'

  - name: "Other Applications"
    icon: "fas fa-database"
    items:
      - name: "Wireshark"
        logo: "assets/logos/wireshark.png"
        type: Ping
        subtitle: "Network protocol analyzer"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:3001"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3000"
        target: '_blank'

      - name: "Pi-hole"
        logo: "assets/logos/pihole.png"
        type: Ping
        subtitle: "DNS and DHCP server"
        url: "http://{{ lookup('file', '/var/run/ip_address') }}:3015"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/http://{{ lookup('file', '/var/run/ip_address') }}:3015"
        target: '_blank'

      - name: "SFTPGo"
        logo: "assets/logos/sftpgo.png"
        type: Ping
        subtitle: "SFTP server"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:3016"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:3016"
        target: '_blank'

      - name: "Chromium"
        logo: "assets/logos/chromium.svg"
        type: Ping
        subtitle: "Web browser"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:4011"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:3011"
        target: '_blank'

      - name: "Syncthing"
        logo: "assets/logos/syncthing.png"
        type: Ping
        subtitle: "File synchronization"
        url: "https://{{ lookup('file', '/var/run/ip_address') }}:4020"
        endpoint: "http://{{ lookup('file', '/var/run/ip_address') }}:3333/https://{{ lookup('file', '/var/run/ip_address') }}:4020"
        target: '_blank'