---
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    hostname: smokeping-netpi
    environment:
      - PUID=1000
      - PGID=1000
      # - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 3017:80
    restart: unless-stopped