---
services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    environment:
      # - TZ=Etc/UTC
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
      - ./config.yml:/config.yml
    networks:
      - traefik

networks:
  traefik:
    external: true