---
version: '3.3'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    environment:
      - TZ=Europe/Zurich
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/docker/traefik/traefik.yml:/traefik.yml"
      - "/opt/docker/traefik/acme.json:/acme.json"
      - "/opt/docker/traefik/config.yml:/config.yml"
    networks:
      - traefik

networks:
  traefik:
    external: true