---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{ timezone }}
      - DB_CONNECTION=sqlite
      - APP_KEY=base64:CRIZG+LPp+BPO4OKoTQwdglzVNoecch5dg9iiJHxkHA=
    volumes:
      - /opt/docker/speedtest-tracker/data:/config
    ports:
      - 4006:80
    restart: unless-stopped