---
services:
  some-sftpgo:
    image: drakkan/sftpgo:latest
    container_name: sftpgo
    restart: unless-stopped
    ports:
      - "3016:8080"
      - "2022:2022"
      - "2121:2121"
      - "50000-50100:50000-50100"
    environment:
      SFTPGO_FTPD__BINDINGS__0__PORT: "2121"
      {% if dash_auto_ip %}
      SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP: "{{ lookup('file', '/var/run/ip_address') }}"
      {% else %}
      SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP: "{{ dash_static_ip }}"
      {% endif %}
    volumes:
      - ./sftpgodata:/srv/sftpgo
      - ./sftpgohome:/var/lib/sftpgo